const fs = require('fs');
const path = require('path');

const queries = [];
let enabled = false;

function enable() {
  enabled = true;
}

function disable() {
  enabled = false;
}

function isEnabled() {
  return enabled;
}

function log(framework, sql, params) {
  if (!enabled) return;
  queries.push({
    framework,
    sql: typeof sql === 'string' ? sql : String(sql),
    params: params || [],
    timestamp: Date.now(),
  });
}

function getQueries() {
  return [...queries];
}

function getAndClear() {
  const snapshot = [...queries];
  queries.length = 0;
  return snapshot;
}

function clear() {
  queries.length = 0;
}

function formatForReport() {
  const byFramework = {};
  for (const q of queries) {
    if (!byFramework[q.framework]) byFramework[q.framework] = [];
    byFramework[q.framework].push(q.sql);
  }
  return byFramework;
}

function writeReport(filePath) {
  const byFramework = formatForReport();
  const frameworks = Object.keys(byFramework);
  const lines = ['# SQL Query Log', '', 'Generated by log-queries.js', ''];

  for (const fw of frameworks) {
    lines.push(`## ${fw}`, '');
    for (const sql of byFramework[fw]) {
      lines.push('```sql');
      lines.push(sql);
      lines.push('```', '');
    }
  }

  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filePath, lines.join('\n'));
  return filePath;
}

module.exports = { enable, disable, isEnabled, log, getQueries, getAndClear, clear, formatForReport, writeReport };
